import { Toaster } from '@/components/ui/sonner'
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-screen h-screen grid place-content-center'>
        <Toaster richColors position="bottom-center"/>
        <main>{children}</main>
      </body>
    </html>
  )
}
